FROM registry.fedoraproject.org/fedora:43
ENV TERM=xterm-256color

#RUN sed -i 's|^metalink=|#metalink=|g' /etc/yum.repos.d/fedora*.repo && \
#    sed -i 's|^#baseurl=.*|baseurl=https://ftp.uni-stuttgart.de/fedora/releases/$releasever/Everything/$basearch/os/|g' /etc/yum.repos.d/fedora.repo && \
#    sed -i 's|^#baseurl=.*|baseurl=https://ftp.uni-stuttgart.de/fedora/updates/$releasever/Everything/$basearch/|g' /etc/yum.repos.d/fedora-updates.repo && \
#   (sed -i 's|^enabled=1|enabled=0|g' /etc/yum.repos.d/fedora-cisco-openh264.repo || true)

COPY install.sh /opt/install.sh
RUN bash /opt/install.sh && rm -f /opt/install.sh

CMD ["/bin/bash"]
